### ISSUE TITLE
We are not lintian warning free

### ISSUE THREAD

**Issue by KaiHa** [KaiHa/nix-debian#10]
To be honest, I am not even sure with which options to run _lintian_ to see all warnings that are considered relevant.

**Comment by infinity0** [comment]
Try `lintian -i -I --pedantic --color auto`, the most important ones are warning and error, everything else is optional but "nice to have". If you have questions about specific ones ask me.

**Comment by KaiHa** [comment]
> If you have questions about specific ones ask me.

Hi @infinity0, thanks for your offer. Indeed I would appreciate your help on #19 and especially #20.
