### ISSUE TITLE
no need to copy full text of LGPL in debian/copyright

### ISSUE THREAD

**Issue by thkoch2001** [KaiHa/nix-debian#11]
The full text of the LGPL-2.1 is available at /usr/share/common-licenses/LGPL-2.1 thus there should be no need to completely include it in debian/copyright.

**Comment by KaiHa** [comment]
That makes sense, does [this][1] look good?

[1]: https://github.com/KaiHa/nix-debian/commit/cd2f4c29973bec28ca64f7d8d2a134c02fc83930
