### ISSUE TITLE
no need to specify copyright for debian/ folder

### ISSUE THREAD

**Issue by thkoch2001** [KaiHa/nix-debian#12]
In my debian packages I usually do not specify the copyright of the files in debian/. So far I haven't packaged anything where the debian/ folder contained substantial work that would qualify (IMHO) to have its own copyright.

However I'm not a lawyer and it's a matter of personal preference.

I'm not aware of any official documentation on this matter.

**Comment by KaiHa** [comment]
That is also OK for me, does [this][1] look good?

[1]: https://github.com/KaiHa/nix-debian/commit/cd2f4c29973bec28ca64f7d8d2a134c02fc83930

**Comment by thkoch2001** [comment]
Much shorter, thank you!

Nit pick: I'd link to https://nixos.org/releases/nix/latest in the `source:` line.

It's still possible to link to the git repo in a comment:
https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/#comment-field

**Comment by KaiHa** [comment]
Thomas Koch <notifications@github.com> writes:

> Nit pick: I'd link to https://nixos.org/releases/nix/latest in the
> `source:` line.

I am unsure. With your proposed change of having the upstream source
code in the master branch, and even now if we use git-buildpackage for
creating the orig-tar-ball wouldn't it be more technical accurate if we
point to the upstream git-repository than pointing to the upstream
tar-ball?

Or is my understanding on how the orig-tar-ball will be created false?

**Comment by thkoch2001** [comment]
I'd still use the released tarball from the upstream project as orig.tar.gz. However I've to admit that I also did my test-build from the Git repo. I need to check whether we see any problems with the tarball when the next version is released.

**Comment by infinity0** [comment]
> In my debian packages I usually do not specify the copyright of the files in debian/.

This is wrong. You are supposed to do that for official Debian packages.

**Comment by infinity0** [comment]
Documentation is here https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/

There is nothing suggesting `debian/*` is exempt so one shouldn't randomly make up exemptions to things. Some of the examples in the doc contain `debian/*` as an explicit example.

**Comment by KaiHa** [comment]
OK, re-added the explicit copyright statement for debian/* in [4db7a6c][1]. Closing this issue now. If there are still improvements necessary, then let us create new issues for better clarity.

[1]: https://github.com/KaiHa/nix-debian/commit/4db7a6c789843ff9fb5a157a598d5311765474cf
