### ISSUE TITLE
consider keeping upstream sources in the master branch

### ISSUE THREAD

**Issue by thkoch2001** [KaiHa/nix-debian#13]
I believe it is now very common in Debian packaging to track upstreams git repository in the packaging branch (master) and just add the debian folder in the same branch.
Have you considered this?

I used your work to create a work-in-progress branch for an official debian package:
https://salsa.debian.org/thk-guest/nix/tree/wip

Would you like us to work together on this kind of repository layout? I understand that we are almost ready to go and just wait for nix upstream to tag a new release?

**Comment by KaiHa** [comment]
Thomas Koch <notifications@github.com> writes:

> I believe it is now very common in Debian packaging to track upstreams
> git repository in the packaging branch (master) and just add the
> debian folder in the same branch.  Have you considered this?

I am still unsure how this is done properly. Would your proposal work
good with git-buildpackage. If yes, then it would be OK for me to track
upstream and debian packaging in one branch.

>
> I used your work to create a work-in-progress branch for an official
> debian package: https://salsa.debian.org/thk-guest/nix/tree/wip

I get a 404 (Page not found) if I follow your link. I am logged in as
guest (kaiha-guest).

>
> Would you like us to work together on this kind of repository layout?
> I understand that we are almost ready to go and just wait for nix
> upstream to tag a new release?

I believe it is still a long way to go. But yes, getting the
upstream release 2.2 would be one step forward. Another one is getting
an exemption for the [non-standard-toplevel-dir][1] (#17) rule.

[1]: https://lintian.debian.org/tags/non-standard-toplevel-dir.html

**Comment by thkoch2001** [comment]
Sorry, you should have developer access now and everybody else read access.
