### ISSUE TITLE
consider multiple binary packages

### ISSUE THREAD

**Issue by thkoch2001** [KaiHa/nix-debian#14]
It is possible to install nix without a global daemon and keep a user-local nix-store. Do you think it'd be a good idea to provide multiple binary packages so that users can decide whether they want a user-local nix-store or a global one, managed by the daemon?

**Comment by thkoch2001** [comment]
$ du -hs /usr/include/nix/
    384K    /usr/include/nix/

I'm not an expert in packaging of C/C++ libraries. Would it make sense to have libnix-dev for the header files or should we have them at all in a package? When there is libnix-dev we should also have libnix2, I suppose?

**Comment by KaiHa** [comment]
Thomas Koch <notifications@github.com> writes:

>     $ du -hs /usr/include/nix/
>     384K    /usr/include/nix/
>
> I'm not an expert in packaging of C/C++ libraries. Would it make sense
> to have libnix-dev for the header files or should we have them at all
> in a package? When there is libnix-dev we should also have libnix2, I
> suppose?

I have no clear opinion on this. But I would like to keep things
simple.

**Comment by KaiHa** [comment]
Thomas Koch <notifications@github.com> writes:

> It is possible to install nix without a global daemon and keep a
> user-local nix-store. Do you think it'd be a good idea to provide
> multiple binary packages so that users can decide whether they want a
> user-local nix-store or a global one, managed by the daemon?

A user-local nix-store would also be unable to use binary substitutes
from the Nix channels (as mentioned in #17).

The standard approach of working without a nix-daemon seems to be a
`/nix/store` that is writable by the user that wants to work with
it. That would IMHO be a ugly solution for a Debian system. I would
prefer to keep things simple and just provide one binary package.
