### ISSUE TITLE
don't install profile scripts

### ISSUE THREAD

**Issue by thkoch2001** [KaiHa/nix-debian#15]
The package currently installs two scripts into /etc/profile.d: nix-daemon.sh and nix.sh, see https://github.com/NixOS/nix/blob/master/scripts/nix-profile-daemon.sh.in and https://github.com/NixOS/nix/blob/master/scripts/nix-profile.sh.in.

I see that profile scripts were discussed before in #5. However I'm concerned to put that much logic into the invocation of every single bash session. Furthermore this does not account for ZSH users.

I'd recommend for an initial debian package to put the scripts into /usr/share/doc/nix/examples and then check how we can maybe eliminate much of the scripts.

In general, nix should assume sane defaults and not need so many environment variables to work, e.g.: NIX_SSL_CERT_FILE: Couldn't there be a configure option to set this?

**Comment by thkoch2001** [comment]
So https://github.com/NixOS/nix/blob/fb35aaa42295940ca8dbfef17b081729636f9775/src/libstore/globals.cc#L50 should work on Debian and we don't need to set NIX_SSL_CERT_FILE?

**Comment by thkoch2001** [comment]
It seems to me that the two shell scripts are mutually exclusive. I tried this now and it does not work:

```
$ nix-channel --update
unpacking channels...
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
error: '/nix/var/nix/profiles/per-user/user/channels' is not a symlink
error: program '/usr/bin/nix-env' failed with exit code 1
```

The issue might be that both scripts set `$NIX_PATH`? I tried with root and a regular user who is member of nix-users with the same result. So I really think we should not include those scripts and think for each variable what the right way is for a Debian package.

**Comment by KaiHa** [comment]
Thomas Koch <notifications@github.com> writes:

> It seems to me that the two shell scripts are mutually exclusive.

Yes, I think you are right. It looks like that we only need to source
nix-daemon.sh.

I need to dig deeper in this.

**Comment by KaiHa** [comment]
Hi @thkoch2001, I did some modifications. Can you test if the situation is now acceptable? If you agree, then I would like to close this issue.

**Comment by thkoch2001** [comment]
Could you reopen this and maybe assign it to me if there is such a feature in GitHub? I still think it's a bug to have both scripts installed but I need to learn more.

**Comment by KaiHa** [comment]
Thomas Koch <notifications@github.com> writes:

> Could you reopen this and maybe assign it to me if there is such a
> feature in GitHub? I still think it's a bug to have both scripts
> installed but I need to learn more.

Only one of the two scripts is installed. At least that was my
[intention][1]. If I failed, then please let me know so I can reopen
this issue.

[1]: https://github.com/KaiHa/nix-debian/commit/1d31a259efa722e750cd5531fa17c4cef7bbe10a
