### ISSUE TITLE
Maybe run garbage-collection as cron-job?

### ISSUE THREAD

**Issue by thkoch2001** [KaiHa/nix-debian#16]
We could add a cron-job (or systemd timer) to regularily run nix-collect-garbage.

I very much prefer systemd timers over cron-jobs but unfortunately there's apparently no best practice yet in debian on how to account for systems without systemd: https://bugs.debian.org/770440. Thus I'd probably go for a cron-job for the moment?

**Comment by KaiHa** [comment]
Thomas Koch <notifications@github.com> writes:

> We could add a cron-job (or systemd timer) to regularily run
> nix-collect-garbage.

The most space is reclaimed by purging old generations. And IMHO this is
something that the user should do deliberately. I assume that a command
like `nix-collect-garbage --delete-older-than 7d` will be used by the
user and this will also remove any unreachable store paths.

**Comment by vcunat** [comment]
> The most space is reclaimed by purging old generations.

The common use case with `nix-shell` for development environments is a bit different in that, as the references get released when you exit the shell.  Still, I'd probably not add such automatic GC enabled by default.
