### ISSUE TITLE
nix unfit for inclusion into Debian due to non-free code

### ISSUE THREAD

**Issue by KaiHa** [KaiHa/nix-debian#2]
Due to [this bug](https://github.com/NixOS/nix/issues/2014) nix contains non-free code that makes it unfit for inclusion into Debian.

**Comment by KaiHa** [comment]
There is a open [PR](https://github.com/NixOS/nix/pull/2228) that might solve this issue.

**Comment by domenkozar** [comment]
Fixed.

**Comment by KaiHa** [comment]
Thanks @domenkozar, I hope I find the time to take a look at it in the following days.
