### ISSUE TITLE
non-standard-toplevel-dir lintian error

### ISSUE THREAD

**Issue by KaiHa** [KaiHa/nix-debian#20]
Lintian complaints:

    E: nix: non-standard-toplevel-dir nix/

As discussed in #17 there are good reasons for having the nix-store at `/nix/store`. We need some sort of exemption from this rule from the Debian project.

**Comment by infinity0** [comment]
Short way: override the error and see if FTP masters complains

Long way: discuss it on debian-devel or debian-policy mailing list

**Comment by KaiHa** [comment]
I try it with the override, let's keep ours fingers crossed.

**Comment by thkoch2001** [comment]
I'd strongly recommend to start the discussion with ftp-masters early. The lintian warning has level error. That means the new-queue will reject the package automatically without any human looking over it. Thus we need to bring this topic to ftp-masters anyways to find a way how to get the package through the new queue without the system rejecting it automatically.

https://ftp-master.debian.org/#lintianrejects says

> error
   Tags listed here can not be overridden. Those are tags corresponding to packaging errors serious enough to mark a package unfit for the archive and should never happen. In fact, most of the tags listed do not appear in our archive currently."

**Comment by stew** [comment]
Former ftp-master here. There is no way that you should be looking for an exception to the FHS. /nix should really be /var/lib/nix in debian or so. I believe that with a lintian  error, the  ftp-masters won't even see the package, its going to get rejected before it ever makes the queue.

**Comment by stew** [comment]
I don't know how possible it is, but if  moving /nix completely is very very hard, then a /nix symlink to /var/lib/nix would be the thing I'd recommend trying. Don't know if this might be any more acceptable to the FTP team, but it seems like it might be a lot closer at least?

**Comment by stew** [comment]
as an aside, I was quite surprised to see that snapd is in the Debian archive with this exception, I raised the severity of the bug tracking that to be release critical so that they'll have to answer about that before the next debian release:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=852199

**Comment by infinity0** [comment]
>  I believe that with a lintian error, the ftp-masters won't even see the package, its going to get rejected before it ever makes the queue.

The error is in the non-fatal list, I'd guess it won't be auto-rejected.

> /nix completely is very very hard, then a /nix symlink to /var/lib/nix would be the thing I'd recommend trying.

Another option would be to `mkdir /nix && echo "/var/lib/nix /nix none defaults,bind 0 0" >> /etc/fstab && mount /nix`.

But honestly `/nix` is just cleaner.

I'd at least add a comment to the override file explaining why it is pointless trying to shoehorn it into the FHS proper, due to build-paths and hashes.

**Comment by infinity0** [comment]
The current round of FTP masters should be somewhat sympathetic to Nix since we're familiar with their work for Reproducible Builds etc and have been in contact with them in general about that.

**Comment by KaiHa** [comment]
Ximin Luo <notifications@github.com> writes:

> I'd at least add a comment to the override file explaining why it is
> pointless trying to shoehorn it into the FHS proper, due to
> build-paths and hashes.

I added a comment in 9012c5a39524d.

**Comment by KaiHa** [comment]
stew <notifications@github.com> writes:

> I don't know how possible it is, but if moving /nix completely is very
> very hard, then a /nix symlink to /var/lib/nix would be the thing I'd
> recommend trying.

I am unsure if a symlink will work in all circumstances. Every binary or
script might have a retained dependency, which is a absolute path to
another script or binary or whatever file. If this full path now contains a
symlink are there some obscure constructs that might fail then? I am not
sure.

**Comment by KaiHa** [comment]
Send out a request to ftpmaster@debian.org today.

**Comment by KaiHa** [comment]
Started a [discussion on debian-devel][1] as proposed by ftpmaster.

[1]: https://lists.debian.org/debian-devel/2019/01/msg00010.html
