### ISSUE TITLE
backport readline patch to latest released nix version

### ISSUE THREAD

**Issue by thkoch2001** [KaiHa/nix-debian#21]
Kai, could you backport your patch for readline support onto the last released version of nix? This way we could just go ahead and prepare a Debian package now instead of waiting for a new upstream release.

**Comment by KaiHa** [comment]
I would prefer to pick a pre-release instead, like what I try [here][1].

[1]: https://github.com/KaiHa/nix-debian/tree/wip/pre-release

**Comment by thkoch2001** [comment]
This is obsolete now since we got a new nix version from upstream since yesterday.
