### ISSUE TITLE
install nix.conf file to /etc/nix

### ISSUE THREAD

**Issue by thkoch2001** [KaiHa/nix-debian#24]
We should provide an empty or commented out nix.conf file so that users can easily see where to make changes. Ideally, The file contains all default settings but commented out and a top-level comment to the manual section: https://nixos.org/nix/manual/#sec-conf-file

Even better would be a man page that explains the conf file.

**Comment by aszlig** [comment]
> Even better would be a man page that explains the conf file.

There is already an upstream [manpage for nix.conf](https://github.com/NixOS/nix/blob/e58a71442ad4a538b48fc7a9938c3690628c4741/doc/manual/command-ref/conf-file.xml).

**Comment by KaiHa** [comment]
> There is already an upstream [manpage for nix.conf](https://github.com/NixOS/nix/blob/e58a71442ad4a538b48fc7a9938c3690628c4741/doc/manual/command-ref/conf-file.xml).

Thanks for pointing that out.
