### ISSUE TITLE
Nix repl has no history

### ISSUE THREAD

**Issue by deliciouslytyped** [KaiHa/nix-debian#28]
I'm not sure what the problem is, but nix repl's history doesn't work. The up arrow key doesn't do anything and no history is recorded.

I poked around with strace a bit and it doesn't seem to be a permissions or missing file issue.

```
lstat("/home/user/.local/share/nix", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
open("/home/user/.local/share/nix/repl-history", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0600, st_size=0, ...}) = 0
read(3, "", 0)                          = 0
close(3)                                = 0
```

Can you reproduce?

**Comment by KaiHa** [comment]
History is working for me on Stretch. Do you have some strange settings in your inputrc (`man readline`)?

**Comment by KaiHa** [comment]
I can reproduce the not working history on Buster :disappointed:

**Comment by deliciouslytyped** [comment]
Thanks :(

**Comment by KaiHa** [comment]
I just created a [pull request][1] that enables the history when compiled against _libreadline_. [This][1] changes have worked for me together with the packaging available at [salsa.d.o][2] on a Debian 10.

[1]: https://github.com/NixOS/nix/pull/3196
[2]: https://salsa.debian.org/debian/nix
