### ISSUE TITLE
nix from /nix/store doesn't work outside NixOS

### ISSUE THREAD

**Issue by infinity0** [KaiHa/nix-debian#3]
Please be aware of https://github.com/NixOS/nix/issues/2372 which makes some things not work on nix-debian.

**Comment by infinity0** [comment]
I have this commit to work around it but I'm not sure it's the best solution: https://github.com/infinity0/nix-debian/commit/23a9c68f7a50b29cdfaf7753ff44f2562c3f9931

**Comment by KaiHa** [comment]
Maybe setting `export NIX_REMOTE=unix:///var/lib/nix/daemon-socket/socket` would already solve this. Let me know if this works for you.

**Comment by infinity0** [comment]
Seems to work OK, thanks!
