### ISSUE TITLE
What's the difference between the package and the nix website install script?

### ISSUE THREAD

**Issue by deliciouslytyped** [KaiHa/nix-debian#30]
The https://nixos.org/nix/install script linked by the "Get Nix" button on https://nixos.org/nix/ gets some archives which also contain some installer scripts. Does this package cover the same things?

**Comment by KaiHa** [comment]
Basically yes. 

Hmm, does this mean you have been unaware of the official Nix installer provided by nixos.org? Maybe I should add a note to the README that points to the official installer.

**Comment by deliciouslytyped** [comment]
I just saw the readme addition. Is there any specific reason this shouldn't be used over the official installer?

**Comment by KaiHa** [comment]
deliciouslytyped <notifications@github.com> writes:

> I just saw the readme addition. Is there any specific reason this shouldn't be used over the official installer?

No specific reason, I just want to make sure that people are aware that
there is an official installer from NixOS available and that this here
is more experimental.
