### ISSUE TITLE
Repository layout

### ISSUE THREAD

**Issue by infinity0** [KaiHa/nix-debian#4]
What's the reasoning for moving everything under `packaging/`? Usual Debian convention is just to put it on the top-level. There is `debian/README.source` as a convention to put source-packaging comments like what's in the current `README.md`.

**Comment by KaiHa** [comment]
I want to have a README that is displayed by Github so people that stumble upon this repository know what this is about and what the current status is. 

But If I put both the _README.md_ (or a .github/README.md) into the same directory as the debian directory then _dpkg-source_ is complaining. So far I have found no other solution to keep _dpkg-source_ (when invoked by _pdebuild_) happy.
