### ISSUE TITLE
Put profile scripts in /etc/X11/Xsession.d as well as /etc/profile.d

### ISSUE THREAD

**Issue by infinity0** [KaiHa/nix-debian#5]
The Debian lightdm maintainer is a bit stubborn about sourcing /etc/profile:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=636108
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=752129

but as an alternative we can also install them to /etc/X11/Xsession.d. They could just be symlinks.

**Comment by KaiHa** [comment]
Hi @infinity0, let me know if this has successfully solved your issue.

**Comment by infinity0** [comment]
Works well, thanks!
