### ISSUE TITLE
The libeditline used by nix is not packed for Debian

### ISSUE THREAD

**Issue by KaiHa** [KaiHa/nix-debian#9]
The [libeditline](http://troglobit.com/projects/editline/) (see [here](https://github.com/NixOS/nix/pull/2228)) that is used by _nix_ is not available on _Debian_. Currently I try to figure out if one of the libraries that is available on _Debian_ is compatible.

**Comment by KaiHa** [comment]
Neither `libeditline`, `libedit2` nor `libreadline` are 100% compatible. Will try my luck with `libreadline`. See here: 

https://github.com/KaiHa/nix/commits/kaiha/libreadline_option
https://github.com/KaiHa/nix-debian/commits/wip/readline

**Comment by KaiHa** [comment]
Created a [pull request](https://github.com/NixOS/nix/pull/2551) to add support for libreadline into nix.

**Comment by KaiHa** [comment]
Pull request was merged. Looking forward to nix 2.2.

**Comment by cyraxjoe** [comment]
@KaiHa did you verified that readline worked as expected? History is not working for me when using `nix repl` . It build and links just fine (debian buster), but the history (and auto complete) is not working. But the repl is not crashing or anything, is simply not writing the history in the history file. 

This is  for the libreadline 7.

**Comment by KaiHa** [comment]
@cyraxjoe, it is working for me on Stretch. I am wondering if I did some configuration in the inputrc (`man readline`), I can't tell for sure. 

Tab completion will not work, that is the only limitation I can remember.

**Comment by KaiHa** [comment]
Hmm, on Buster history is also not working for me. I will be tracking this in #28.
